server.port=8898
spring.application.name=loan-service

# POSTGRES
spring.datasource.url=jdbc:postgresql://localhost:5432/myfin_loan_db
spring.datasource.username=postgres
spring.datasource.password=slk@SOFT123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# BASIC SECURITY (optional)
spring.security.user.name=umesh
spring.security.user.password=umesh123

# ACTUATOR
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ? EUREKA CLIENT CONFIG
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true